# serverless.yml

service: scrapeogp-lambda
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
functions:
  graphql:
    name: graphql
    handler: build/app.graphqlHandler
    environment:
      LAMBDA: "true"
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-offline
